### ISSUE TITLE
1.16.2 Weapons' effects dont work

### ISSUE THREAD

**Issue by Arturitu12** [catocatocat0/MWEPs#1]
Hi i have server on 1.16.2 Spigot, native 2 wepons works but display invalid ammo type, custom wepons i made or copy from examaples dont harms a player, espieccially this ones with effects. if i hit them normal way they harm so this not my others plugins' protection. Can i get some help? thx

**Comment by DarkVanityOfLight** [comment]
Could you maybe post your weapons file?

**Comment by catocatocat0** [comment]
Yes, could you post the weapon file. Sorry for replying so late.

**Comment by DarkVanityOfLight** [comment]
I think you should close this, lmao
